// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcp.actions;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaAssociation;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;
import java.math.BigDecimal;
import com.mendix.systemwideinterfaces.core.UserAction;

public class InsertDataFromJSON extends UserAction<java.lang.Boolean>
{
	public InsertDataFromJSON(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        boolean hasErrors = false;

        try {
            Path actualResourcePath = Paths.get(Core.getConfiguration().getResourcesPath().toString());
            Path basePath = actualResourcePath.getParent().getParent().getParent();
            Path resourcePath = basePath.resolve("resources");

            String logFilePath = resourcePath.resolve("import_log.txt").toString();
            initializeLogFile(logFilePath);

            try (DirectoryStream<Path> directoryStream = Files.newDirectoryStream(resourcePath, "*.json")) {
                for (Path path : directoryStream) {
                    boolean fileHasErrors = processFile(path);
                    if (fileHasErrors) {
                        hasErrors = true;
                        writeLog("WARNING: File " + path.getFileName() + " had errors — file NOT deleted for debugging");
                    } else {
                        Files.delete(path);
                        writeLog("Completed processing file: " + path.getFileName() + " — file deleted");
                    }
                }
            }

        } catch (Exception e) {
            writeLog("Fatal error: " + e.getMessage());
            e.printStackTrace(logFile);
            hasErrors = true;
        } finally {
            closeLogFile();
        }

        return !hasErrors;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InsertDataFromJSON";
	}

	// BEGIN EXTRA CODE
    private final ILogNode logger = Core.getLogger("InsertDataFromJSON");
    private PrintWriter logFile = null;
    private final Map<String, Map<String, ObjectInfo>> virtualIdMap = new HashMap<>();

    // V2 metadata fields
    private JSONObject metadata = null;
    private JSONObject metadataAssociations = null;
    private JSONObject metadataEntities = null;
    private int formatVersion = 1;

    // Counters for summary
    private int totalRecordsCreated = 0;
    private int totalAssociationsCreated = 0;
    private int totalErrors = 0;

    private static class ObjectInfo {
        final IMendixObject object;
        final String internalId;

        ObjectInfo(IMendixObject object) {
            this.object = object;
            this.internalId = object.getId().toString();
        }
    }

    private boolean processFile(Path path) {
        boolean fileHasErrors = false;
        totalRecordsCreated = 0;
        totalAssociationsCreated = 0;
        totalErrors = 0;
        virtualIdMap.clear();
        metadata = null;
        metadataAssociations = null;
        metadataEntities = null;
        formatVersion = 1;

        try {
            writeLog("\nProcessing file: " + path.getFileName());

            String content = new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
            JSONObject rootObject = new JSONObject(content);

            // Parse metadata if present (v2 format)
            if (rootObject.has("_metadata")) {
                metadata = rootObject.getJSONObject("_metadata");
                formatVersion = metadata.optInt("version", 1);
                metadataAssociations = metadata.optJSONObject("associations");
                metadataEntities = metadata.optJSONObject("entities");
                writeLog("Detected v" + formatVersion + " format with metadata");
                if (metadataAssociations != null) {
                    writeLog("  Associations defined: " + metadataAssociations.length());
                }
                if (metadataEntities != null) {
                    writeLog("  Entities with metadata: " + metadataEntities.length());
                }
            } else {
                writeLog("No _metadata found — using v1 legacy format");
            }

            // Get data object (support both "Data" and "data" keys)
            JSONObject dataObject;
            if (rootObject.has("data")) {
                dataObject = rootObject.getJSONObject("data");
            } else if (rootObject.has("Data")) {
                dataObject = rootObject.getJSONObject("Data");
            } else {
                writeLog("ERROR: No 'data' or 'Data' key found in JSON root");
                return true;
            }

            // First pass: Create all entities
            writeLog("\n--- Pass 1: Creating entities ---");
            for (String entityName : dataObject.keySet()) {
                JSONArray entityArray = dataObject.getJSONArray(entityName);
                boolean entityErrors = processEntities(entityName, entityArray);
                if (entityErrors) fileHasErrors = true;
            }

            // Second pass: Process all associations
            writeLog("\n--- Pass 2: Processing associations ---");
            if (formatVersion >= 2 && metadataAssociations != null) {
                boolean assocErrors = processAssociationsV2(dataObject);
                if (assocErrors) fileHasErrors = true;
            } else {
                boolean assocErrors = processAssociationsV1(dataObject);
                if (assocErrors) fileHasErrors = true;
            }

            // Summary
            writeLog("\n--- Import Summary ---");
            writeLog("Records created: " + totalRecordsCreated);
            writeLog("Associations linked: " + totalAssociationsCreated);
            writeLog("Errors encountered: " + totalErrors);
            if (totalErrors > 0) {
                fileHasErrors = true;
            }

        } catch (Exception e) {
            writeLog("Fatal error processing file: " + e.getMessage());
            e.printStackTrace(logFile);
            fileHasErrors = true;
        }

        return fileHasErrors;
    }

    // --- Logging ---

    private void initializeLogFile(String logFilePath) throws IOException {
        logFile = new PrintWriter(new FileWriter(logFilePath, true));
        writeLog("\n" + "=".repeat(50));
        writeLog("Import started at: " + new Date());
        writeLog("=".repeat(50));
    }

    private void closeLogFile() {
        if (logFile != null) {
            logFile.close();
        }
    }

    private void writeLog(String message) {
        logger.info(message);
        if (logFile != null) {
            logFile.println(message);
            logFile.flush();
        }
    }

    // --- Pass 1: Entity creation ---

    private boolean processEntities(String entityName, JSONArray records) {
        boolean hasErrors = false;
        try {
            writeLog("Creating " + records.length() + " " + entityName + " records");

            for (int i = 0; i < records.length(); i++) {
                try {
                    JSONObject record = records.getJSONObject(i);
                    IMendixObject obj = Core.instantiate(getContext(), entityName);
                    updateMendixObject(getContext(), entityName, record, obj);
                    Core.commit(getContext(), obj);

                    if (record.has("VirtualId")) {
                        String virtualId = record.getString("VirtualId");
                        ObjectInfo objectInfo = new ObjectInfo(obj);
                        virtualIdMap.computeIfAbsent(entityName, k -> new HashMap<>())
                                  .put(virtualId, objectInfo);
                    }
                    totalRecordsCreated++;
                } catch (Exception e) {
                    writeLog("  ERROR creating record " + i + " of " + entityName + ": " + e.getMessage());
                    e.printStackTrace(logFile);
                    totalErrors++;
                    hasErrors = true;
                }
            }
        } catch (Exception e) {
            writeLog("ERROR processing entity type " + entityName + ": " + e.getMessage());
            e.printStackTrace(logFile);
            totalErrors++;
            hasErrors = true;
        }
        return hasErrors;
    }

    private void updateMendixObject(IContext context, String entityName, JSONObject item, IMendixObject mendixObject) {
        for (Iterator<String> jsonNames = item.keys(); jsonNames.hasNext(); ) {
            String jsonName = jsonNames.next();
            // Skip VirtualId, null values, association references, and metadata keys
            if (item.isNull(jsonName) || jsonName.equals("VirtualId") || jsonName.equals("_associations")) {
                continue;
            }

            try {
                Object value = item.get(jsonName);
                // In v1 format, skip JSONObject values (association references)
                // In v2 format, all association refs are under _associations so no JSONObject attrs here
                if (value instanceof JSONObject) {
                    continue;
                }
                setAttributeValue(mendixObject, entityName, jsonName, value);
            } catch (Exception e) {
                writeLog("  Warning: attribute " + jsonName + " on " + entityName + ": " + e.getMessage());
            }
        }
    }

    // --- Pass 2: Association processing (V2 — metadata-driven) ---

    private boolean processAssociationsV2(JSONObject dataObject) {
        boolean hasErrors = false;
        try {
            for (String entityName : dataObject.keySet()) {
                JSONArray records = dataObject.getJSONArray(entityName);

                for (int i = 0; i < records.length(); i++) {
                    JSONObject record = records.getJSONObject(i);
                    if (!record.has("VirtualId") || !record.has("_associations")) continue;

                    String sourceVirtualId = record.getString("VirtualId");
                    Map<String, ObjectInfo> sourceMap = virtualIdMap.get(entityName);
                    if (sourceMap == null) continue;
                    ObjectInfo sourceInfo = sourceMap.get(sourceVirtualId);
                    if (sourceInfo == null) continue;

                    JSONObject associations = record.getJSONObject("_associations");
                    for (String assocQualifiedName : associations.keySet()) {
                        try {
                            JSONObject assocRef = associations.getJSONObject(assocQualifiedName);
                            String targetVirtualId = assocRef.getString("VirtualId");

                            // Look up association metadata
                            if (metadataAssociations == null || !metadataAssociations.has(assocQualifiedName)) {
                                writeLog("  Warning: association " + assocQualifiedName + " not found in metadata — skipping");
                                continue;
                            }

                            JSONObject assocMeta = metadataAssociations.getJSONObject(assocQualifiedName);
                            String parentEntityName = assocMeta.getString("parent");
                            String childEntityName = assocMeta.getString("child");

                            // Determine which entity is the source and which is the target
                            // The association is stored on the parent (owner) entity
                            String targetEntityName;
                            IMendixObject ownerObject;
                            IMendixObject referencedObject;

                            if (entityName.equals(parentEntityName)) {
                                // Source is the parent (owner) — target is child
                                targetEntityName = childEntityName;
                                Map<String, ObjectInfo> targetMap = virtualIdMap.get(targetEntityName);
                                if (targetMap == null || !targetMap.containsKey(targetVirtualId)) {
                                    writeLog("  Warning: target " + targetEntityName + " VirtualId=" + targetVirtualId + " not found");
                                    continue;
                                }
                                ownerObject = sourceInfo.object;
                                referencedObject = targetMap.get(targetVirtualId).object;
                            } else if (entityName.equals(childEntityName)) {
                                // Source is the child — target is parent (owner)
                                targetEntityName = parentEntityName;
                                Map<String, ObjectInfo> targetMap = virtualIdMap.get(targetEntityName);
                                if (targetMap == null || !targetMap.containsKey(targetVirtualId)) {
                                    writeLog("  Warning: target " + targetEntityName + " VirtualId=" + targetVirtualId + " not found");
                                    continue;
                                }
                                ownerObject = targetMap.get(targetVirtualId).object;
                                referencedObject = sourceInfo.object;
                            } else {
                                writeLog("  Warning: entity " + entityName + " is neither parent nor child of " + assocQualifiedName);
                                continue;
                            }

                            // Set the association on the owner (parent) object
                            ownerObject.setValue(getContext(), assocQualifiedName, referencedObject.getId());
                            Core.commit(getContext(), ownerObject);
                            totalAssociationsCreated++;
                            writeLog("  Linked: " + assocQualifiedName + " (owner=" + parentEntityName + ")");

                        } catch (Exception e) {
                            writeLog("  ERROR linking association " + assocQualifiedName + ": " + e.getMessage());
                            e.printStackTrace(logFile);
                            totalErrors++;
                            hasErrors = true;
                        }
                    }
                }
            }
        } catch (Exception e) {
            writeLog("ERROR in v2 association processing: " + e.getMessage());
            e.printStackTrace(logFile);
            totalErrors++;
            hasErrors = true;
        }
        return hasErrors;
    }

    // --- Pass 2: Association processing (V1 — legacy guessing) ---

    private boolean processAssociationsV1(JSONObject rootObject) {
        boolean hasErrors = false;
        try {
            writeLog("Using v1 legacy association resolution");

            for (String entityName : rootObject.keySet()) {
                JSONArray records = rootObject.getJSONArray(entityName);
                String moduleName = entityName.substring(0, entityName.lastIndexOf("."));

                for (int i = 0; i < records.length(); i++) {
                    JSONObject record = records.getJSONObject(i);
                    if (!record.has("VirtualId")) continue;
                    String sourceVirtualId = record.getString("VirtualId");

                    Map<String, ObjectInfo> sourceEntityMap = virtualIdMap.get(entityName);
                    if (sourceEntityMap == null) continue;
                    ObjectInfo sourceInfo = sourceEntityMap.get(sourceVirtualId);
                    if (sourceInfo == null) continue;

                    IMendixObject sourceObject = sourceInfo.object;

                    for (Iterator<String> jsonNames = record.keys(); jsonNames.hasNext();) {
                        String jsonName = jsonNames.next();
                        if (record.isNull(jsonName) || jsonName.equals("VirtualId") || jsonName.equals("_associations")) {
                            continue;
                        }

                        Object value = record.get(jsonName);
                        if (value instanceof JSONObject) {
                            try {
                                JSONObject associationRef = record.getJSONObject(jsonName);
                                if (!associationRef.has("VirtualId")) continue;
                                String targetVirtualId = associationRef.getString("VirtualId");
                                String targetEntityName = moduleName + "." + jsonName;

                                Map<String, ObjectInfo> targetMap = virtualIdMap.get(targetEntityName);
                                if (targetMap != null && targetMap.containsKey(targetVirtualId)) {
                                    ObjectInfo targetInfo = targetMap.get(targetVirtualId);
                                    IMendixObject targetObject = targetInfo.object;
                                    IMetaObject targetMetaObject = targetObject.getMetaObject();

                                    boolean linked = false;
                                    for (IMetaAssociation association : targetMetaObject.getDeclaredMetaAssociationsParent()) {
                                        if (association.getChild().getName().equals(entityName)) {
                                            targetObject.setValue(getContext(), association.getName(),
                                                               sourceObject.getId());
                                            Core.commit(getContext(), targetObject);
                                            totalAssociationsCreated++;
                                            writeLog("  Linked (v1): " + targetEntityName + " -> " + entityName);
                                            linked = true;
                                            break;
                                        }
                                    }
                                    if (!linked) {
                                        // Try the other direction
                                        IMetaObject sourceMetaObject = sourceObject.getMetaObject();
                                        for (IMetaAssociation association : sourceMetaObject.getDeclaredMetaAssociationsParent()) {
                                            if (association.getChild().getName().equals(targetEntityName)) {
                                                sourceObject.setValue(getContext(), association.getName(),
                                                                   targetObject.getId());
                                                Core.commit(getContext(), sourceObject);
                                                totalAssociationsCreated++;
                                                writeLog("  Linked (v1 reverse): " + entityName + " -> " + targetEntityName);
                                                linked = true;
                                                break;
                                            }
                                        }
                                    }
                                    if (!linked) {
                                        writeLog("  Warning: could not find association between " + entityName + " and " + targetEntityName);
                                    }
                                } else {
                                    writeLog("  Warning: target " + targetEntityName + " VirtualId=" + targetVirtualId + " not found");
                                }
                            } catch (Exception e) {
                                writeLog("  ERROR linking v1 association " + jsonName + ": " + e.getMessage());
                                totalErrors++;
                                hasErrors = true;
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            writeLog("ERROR in v1 association processing: " + e.getMessage());
            e.printStackTrace(logFile);
            totalErrors++;
            hasErrors = true;
        }
        return hasErrors;
    }

    // --- Attribute value setting ---

    private void setAttributeValue(IMendixObject obj, String entityName, String attributeName, Object value) {
        try {
            if (value == null) return;

            IMetaPrimitive primitive = obj.getMetaObject().getMetaPrimitive(attributeName);
            if (primitive == null) {
                writeLog("  Warning: attribute '" + attributeName + "' not found on " + entityName + " — skipping");
                return;
            }

            switch (primitive.getType()) {
                case Boolean:
                    if (value instanceof Boolean) {
                        obj.setValue(getContext(), attributeName, (Boolean) value);
                    } else {
                        obj.setValue(getContext(), attributeName, Boolean.parseBoolean(value.toString()));
                    }
                    break;
                case DateTime:
                    String dateStr = value.toString();
                    // Strip trailing Z for SimpleDateFormat compatibility
                    if (dateStr.endsWith("Z")) {
                        dateStr = dateStr.substring(0, dateStr.length() - 1);
                    }
                    // Strip milliseconds if present
                    int dotIndex = dateStr.lastIndexOf('.');
                    if (dotIndex > 0) {
                        dateStr = dateStr.substring(0, dotIndex);
                    }
                    Date date = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss").parse(dateStr);
                    obj.setValue(getContext(), attributeName, date);
                    break;
                case Decimal:
                    obj.setValue(getContext(), attributeName, new BigDecimal(value.toString()));
                    break;
                case Enum:
                    String enumValue = value.toString();
                    // Try to set the enum value directly (works for unqualified names like "Delivered")
                    try {
                        obj.setValue(getContext(), attributeName, enumValue);
                    } catch (Exception enumEx) {
                        // If that fails, try looking up qualified enum name from metadata
                        String qualifiedValue = resolveEnumValue(entityName, attributeName, enumValue);
                        if (qualifiedValue != null && !qualifiedValue.equals(enumValue)) {
                            obj.setValue(getContext(), attributeName, qualifiedValue);
                        } else {
                            throw enumEx; // Re-throw original
                        }
                    }
                    break;
                case Integer:
                    if (value instanceof Integer) {
                        obj.setValue(getContext(), attributeName, (Integer) value);
                    } else {
                        obj.setValue(getContext(), attributeName, Integer.parseInt(value.toString()));
                    }
                    break;
                case Long:
                    if (value instanceof Long) {
                        obj.setValue(getContext(), attributeName, (Long) value);
                    } else {
                        obj.setValue(getContext(), attributeName, Long.parseLong(value.toString()));
                    }
                    break;
                case String:
                    String strValue = value.toString();
                    // Handle unicode escape for plus sign
                    if (strValue.contains("\\u002B")) {
                        strValue = strValue.replace("\\u002B", "+");
                    }
                    obj.setValue(getContext(), attributeName, strValue);
                    break;
                default:
                    obj.setValue(getContext(), attributeName, value);
                    break;
            }
        } catch (Exception e) {
            writeLog("  ERROR setting " + entityName + "." + attributeName + " = " + value + ": " + e.getMessage());
            totalErrors++;
        }
    }

    /**
     * Resolve an enum value using v2 metadata if available.
     * Returns null if metadata is not available or enum not found.
     */
    private String resolveEnumValue(String entityName, String attributeName, String value) {
        if (metadataEntities == null) return null;

        try {
            if (metadataEntities.has(entityName)) {
                JSONObject entityMeta = metadataEntities.getJSONObject(entityName);
                if (entityMeta.has("attributes")) {
                    JSONObject attributes = entityMeta.getJSONObject("attributes");
                    if (attributes.has(attributeName)) {
                        JSONObject attrMeta = attributes.getJSONObject(attributeName);
                        if (attrMeta.has("enum_name")) {
                            // enum_name is like "MyFirstModule.OrderStatus"
                            // Mendix enum values are set as just the value name (e.g., "Delivered")
                            // But if that failed, we don't have another format to try
                            writeLog("  Note: enum " + attrMeta.getString("enum_name") + " value '" + value + "' rejected by runtime");
                        }
                    }
                }
            }
        } catch (Exception e) {
            // Metadata lookup failed, return null
        }
        return null;
    }
	// END EXTRA CODE
}
